CREATE TYPE "GENERO" AS ENUM (
  'HOMBRE',
  'MUJER'
);

CREATE TYPE "MODALIDAD" AS ENUM (
  'PRESENCIAL',
  'SEMIPRESENCIAL'
);

CREATE TYPE "ESTADO_ALUMNO" AS ENUM (
  'VIGENTE',
  'EGRESADO',
  'BAJA_TEMPORAL',
  'BAJA_DEFINITIVA'
);

CREATE TABLE "FACTORES_DE_RIESGO" (
  "ID" SERIAL PRIMARY KEY,
  "NOMBRE" "VARCHAR(64)" NOT NULL
);

CREATE TABLE "CARRERAS" (
  "ID" SERIAL PRIMARY KEY,
  "NOMBRE" "VARCHAR(64)" NOT NULL,
  "MODALIDAD" "MODALIDAD" NOT NULL
);

CREATE TABLE "ALUMNOS" (
  "NO_CONTROL" "VARCHAR(16)" PRIMARY KEY,
  "NOMBRE" "VARCHAR(64)" NOT NULL,
  "APELLIDO_PATERNO" "VARCHAR(64)" NOT NULL,
  "APELLIDO_MATERNO" "VARCHAR(64)",
  "GENERO" "GENERO" NOT NULL,
  "ESTADO" "ESTADO_ALUMNO" NOT NULL,
  "SEMESTRE" INT NOT NULL,
  "ID_CARRERA" INT NOT NULL
);

CREATE TABLE "FACTORES_POR_ALUMNO" (
  "ID" SERIAL PRIMARY KEY,
  "ID_FACTOR" INT NOT NULL,
  "NO_CONTROL_ALUMNO" "VARCHAR(16)" NOT NULL
);

CREATE TABLE "MATERIAS" (
  "ID" SERIAL PRIMARY KEY,
  "NOMBRE" "VARCHAR(64)" NOT NULL,
  "SERIE" "VARCHAR(64)" NOT NULL,
  "UNIDADES" INT NOT NULL
);

CREATE TABLE "GRUPOS" (
  "ID" SERIAL PRIMARY KEY,
  "GRUPO" "VARCHAR(16)",
  "ID_MATERIA" INT NOT NULL
);

CREATE TABLE "MATERIAS_POR_CARRERA" (
  "ID" SERIAL PRIMARY KEY,
  "ID_MATERIA" INT NOT NULL,
  "ID_CARRERA" INT NOT NULL
);

CREATE TABLE "INSCRIPCIONES" (
  "ID" SERIAL PRIMARY KEY,
  "ID_GRUPO" INT NOT NULL,
  "NO_CONTROL_ALUMNO" "VARCHAR(16)" NOT NULL
);

CREATE TABLE "CALIFICACIONES" (
  "ID" SERIAL PRIMARY KEY,
  "UNIDAD" INT NOT NULL,
  "CALIFICACION" INT NOT NULL,
  "FALTAS" INT NOT NULL,
  "ID_INSCRIPCION" INT NOT NULL
);

ALTER TABLE "ALUMNOS" ADD FOREIGN KEY ("ID_CARRERA") REFERENCES "CARRERAS" ("ID");

ALTER TABLE "FACTORES_POR_ALUMNO" ADD FOREIGN KEY ("ID_FACTOR") REFERENCES "FACTORES_DE_RIESGO" ("ID");

ALTER TABLE "FACTORES_POR_ALUMNO" ADD FOREIGN KEY ("NO_CONTROL_ALUMNO") REFERENCES "ALUMNOS" ("NO_CONTROL");

ALTER TABLE "GRUPOS" ADD FOREIGN KEY ("ID_MATERIA") REFERENCES "MATERIAS" ("ID");

ALTER TABLE "MATERIAS_POR_CARRERA" ADD FOREIGN KEY ("ID_MATERIA") REFERENCES "MATERIAS" ("ID");

ALTER TABLE "MATERIAS_POR_CARRERA" ADD FOREIGN KEY ("ID_CARRERA") REFERENCES "CARRERAS" ("ID");

ALTER TABLE "INSCRIPCIONES" ADD FOREIGN KEY ("ID_GRUPO") REFERENCES "GRUPOS" ("ID");

ALTER TABLE "INSCRIPCIONES" ADD FOREIGN KEY ("NO_CONTROL_ALUMNO") REFERENCES "ALUMNOS" ("NO_CONTROL");

ALTER TABLE "CALIFICACIONES" ADD FOREIGN KEY ("ID_INSCRIPCION") REFERENCES "INSCRIPCIONES" ("ID");